```{r}
link='https://github.com/EvansDataScience/VisualAnalytics_2_tabularData/raw/master/data/eduwa.rda'
load(file=url(link))
```

```{r}
dim(eduwa)
```

```{r}
names(eduwa)
```

```{r}
str(eduwa,width = 70,strict.width='cut')
```

```{r}
head(eduwa$LocaleType,50)
```

```{r}
table(eduwa$LocaleType,exclude = 'nothing')
```

```{r}
absoluteT=table(eduwa$LocaleType,exclude = 'nothing')
prop.table(absoluteT)
```

```{r}
ToPlot=prop.table(absoluteT)
pie(ToPlot)
```

```{r}
names(ToPlot)
```

```{r}
names(ToPlot)[5]='Unknown'
```

```{r}
titleText='Where are Public Schools located in WA in 2019?'
sourceText='Source: US Department of Education'

pie(ToPlot,
    main=titleText,
    sub=sourceText)
```

```{r}
titleText2='WA still has schools locations unknown \n (info from 2018)'

pie(ToPlot,
    main=titleText2,
    sub=sourceText)
```

```{r}
titleText3='WA needs to fully categorize school locations\n(info from 2018)'

pie(ToPlot,
    main=titleText3,
    sub=sourceText)
```

```{r}
ToPlot*100
```

```{r}
ToPlot=ToPlot*100
paletteHere=rainbow(length(ToPlot))
pie(x=ToPlot,
    col = paletteHere, 
    labels = ToPlot,
    main=titleText,
    sub=sourceText)
```

```{r}
paste0(round(ToPlot,2),'%')
```

```{r}
plotLabels=paste0(round(ToPlot,2),'%')
pie(x=ToPlot,
    col = paletteHere, 
    labels = plotLabels,
    main=titleText,
    sub=sourceText)
```

```{r}
pie(x=ToPlot,
      col = paletteHere, 
    labels = plotLabels,
    main=titleText,
    sub=sourceText)
legend(x="right",
       legend=names(ToPlot),
        fill = paletteHere)


```

```{r}
pie(x=ToPlot,
    col = paletteHere, 
    labels = plotLabels,
    main=titleText,
    sub=sourceText)
legend(x="right", 
       legend=names(ToPlot), 
       fill = paletteHere,
       bty = 'n', 
       cex = 0.5  
       ) 
```

```{r}
barplot(ToPlot,
         col = paletteHere,
         main=titleText,
         sub=sourceText)
```

```{r}
paletteHereNew=c('gray') 
barplot(ToPlot,
     col = paletteHereNew,
     border=NA, 
     main=titleText,
     sub=sourceText,
     ylim=c(0,50),
     ylab = '(in %)' 
     )
```

```{r}
location=barplot(ToPlot,
     col = paletteHereNew,
     border=NA,
     main=titleText,
     sub=sourceText,
     ylim=c(0,50),
     ylab = '(in %)')
text(x=location,y=ToPlot,labels=plotLabels,
     pos = 1,
     cex = 0.8) 
```

```{r}
location=barplot(ToPlot,
     col = paletteHereNew,
     border=NA,
     main=titleText,
     sub=sourceText,
     ylim=c(0,50),
     ylab = '(in %)',
     horiz = T)
text(x=location,y=ToPlot,labels=plotLabels,
     pos = 1)

```

```{r}
location=barplot(ToPlot,
         col = paletteHereNew,
         border=NA,
         main=titleText,
         sub=sourceText,
         xlim=c(0,50),
         xlab = '(in %)', 
         horiz = T)

text(x=ToPlot,y=location, 
     labels=plotLabels,
     pos = 4)
```

```{r}
location=barplot(ToPlot,
         col = paletteHereNew,
         border=NA,
         main=titleText,
         sub=sourceText,
         cex.names = 0.7, 
         xlim=c(0,50), 
         xlab = '(in %)', 
         horiz = T)
text(x=ToPlot,y=location,labels=plotLabels,pos = 4) 
```

```{r}
location=barplot(ToPlot,
         col = paletteHereNew,
         border=NA,
         main=titleText, 
         xlim=c(0,50), 
         cex.names = 0.5,
         xlab = '(in %)', 
         horiz = T)
text(x=ToPlot,y=location,labels=plotLabels,pos = 4)  
title(sub=sourceText, 
      adj=0,
      cex.sub=0.7) 
```

```{r}
par(mgp=c(0.5,0.5,0))
location=barplot(ToPlot,
         col = paletteHereNew,
         border=NA,
         main=titleText,
         xlim=c(0,50), 
         xlab = '(in %)',
         cex.names = 0.6,
         cex.lab=0.6, 
         horiz = T) 
text(x=ToPlot,y=location,labels=plotLabels,pos = 4) 
title(sub=sourceText, adj=0,cex.sub=0.7,
      line = 3)
```

```{r}
titleText2='Are all locations getting a fair share of public schools in WA?'
par(mgp=c(1,0.5,0)) 
location=barplot(ToPlot,
         col = paletteHereNew,
         border=NA,
         main=titleText2,
         xlim=c(0,50), 
         cex.names = 0.6,
         cex.lab=0.6,
         xlab = '(in %)',
         horiz = T
         ) 
text(x=ToPlot,y=location,labels=plotLabels,pos = 4) 
title(sub=sourceText, adj=0,cex.sub=0.7,
      line = 3) 
abline(v=25,
       lty=3,
       lwd=3)
```

```{r}
par(mgp=c(1,0.5,0)) 
location=barplot(ToPlot,
         col = paletteHereNew,
         border=NA,
         main=titleText2,
         xlim=c(0,50), 
         xlab = '(in %)',
         cex.names=0.6,
         cex.lab=0.6,
         las=2,
         horiz = T,
         xaxt="n") 
text(x=ToPlot,y=location,labels=plotLabels,pos = 4,cex = 0.7) 
title(sub=sourceText, adj=0,cex.sub=0.7,line = 3) 
abline(v=25,lty=3,lwd=3)
newXvalues<-c(0,10,25,40,50) 
axis(side=1, 
     at=newXvalues, 
     labels = newXvalues,
     cex.axis=0.8)
```

```{r}
tableFreq=as.data.frame(ToPlot)
names(tableFreq)=c("locale","pct")

tableFreq
```

```{r}
library(ggplot2)
```

```{r}
base= ggplot(data = tableFreq, 
             aes(x = locale,
                 y = pct)) 
```

```{r}
plot1 = base + geom_bar(fill ="gray",
                        stat = 'identity') 
plot1
```

```{r}
plot2 = plot1 + labs(title=titleText2,
                     x =NULL, 
                     y = NULL,
                     caption = sourceText)
plot2
```

```{r}
plot3 = plot2 + geom_hline(yintercept = 25, 
                           linetype="dashed", 
                           size=1.5, 
                           alpha=0.5) 
plot3
```

```{r}
library(scales)
plot4 = plot3 + scale_y_continuous(breaks=c(0,10, 25,40,50),
                                 limits = c(0, 50), ,
                                 labels=scales::unit_format(suffix = '%')) 
plot4
```

```{r}
plot5 = plot4 + theme(panel.background = element_rect(fill = "white",
                                                    colour = "grey50"),
                    plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5))
plot5
```

```{r}
plot6 = plot5 + geom_text(aes(y = pct ,
                            label = paste0(round(pct,2), '%')),
                        vjust=1, 
                        size = 3)

plot6 #+ coord_flip()
```

```{r}
ToPlotOrd=sort(ToPlot)
plotLabels=paste0(round(ToPlotOrd,2),'%') 

par(mgp=c(1,0.5,0)) 
location=barplot(ToPlotOrd,
         col = paletteHereNew,
         border=NA,
         main=titleText2,
         xlim=c(0,50), 
         xlab = '(in %)',
         horiz = T,
         cex.names = 0.7,
         cex.lab=0.6,
         xaxt="n") 

text(x=ToPlotOrd,y=location,labels=plotLabels,pos = 4,cex = 0.7) 
title(sub=sourceText, adj=0,cex.sub=0.7,line = 3) 

abline(v=25,lty=3,lwd=3)

xtick<-c(0,10,25,40,50)
axis(side=1, at=xtick, labels = xtick,cex.axis=0.8)
```

```{r}
tableFreqO=tableFreq[order(-tableFreq$pct),]
tableFreqO
```

```{r}
tableFreq[order(-tableFreq$pct),]
base= ggplot(data = tableFreq, 
             aes(x = reorder(locale, -pct),
                 y = pct)) 

plot1 = base + geom_bar(fill ="green",
                        stat = 'identity') # y is just what it is!

plot2 = plot1 + labs(title=titleText,
                     x =NULL, 
                     y = NULL,
                     caption = sourceText)

plot3 = plot2 + geom_hline(yintercept = 25, #where
                           linetype="dashed", 
                           size=1.5, #thickness
                           alpha=0.5) #transparency
library(scales)

# customize Y axis
plot4 = plot3 + scale_y_continuous(breaks=c(0,10, 25,40,50),
                                 limits = c(0, 50),
                                 labels=scales::unit_format(suffix = '%')) 
plot5 = plot4 + theme(panel.background = element_rect(fill = "white",
                                                    colour = "grey50"),
                    plot.caption = element_text(hjust = 0), # default was 1
                    plot.title = element_text(hjust = 0.5))

plot6 = plot5 + geom_text(aes(y = pct ,
                            label = paste0(round(pct,2), '%')),
                        vjust=1, # if flipping 'hjust'
                        size = 3)

plot6
plot6 + coord_flip()
```

```{r}
base= ggplot(data = tableFreqO, 
             aes(x = locale,
                 y = pct)) 


plot1 = base + geom_bar(fill ="gray",
                        stat = 'identity') + scale_x_discrete(limits=tableFreqO$locale) 
plot1 
```

```{r}
plot2 = plot1 + labs(title=titleText2,
                     x =NULL, 
                     y = NULL,
                     caption = sourceText)
plot2
```

```{r}
plot3 = plot2 + geom_hline(yintercept = 25, #where
                           linetype="dashed", 
                           size=1.5, #thickness
                           alpha=0.5) #transparency
plot3
```

```{r}
library(scales)

plot4 = plot3 + scale_y_continuous(breaks=c(0,10, 25,40,50),
                                 limits = c(0, 50),
                                 labels=scales::unit_format(suffix = '%')) 
plot4
```

```{r}
plot5 = plot4 + theme(panel.background = element_rect(fill = "white",
                                                    colour = "grey50"),
                    plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5))
plot5
```

```{r}
plot6 = plot5 + geom_text(aes(y = pct ,
                            label = paste0(round(pct,2), '%')),
                        vjust=1, 
                        size = 3)
plot6 #+ coord_flip()
```

```{r}
plot6 = plot5 + geom_text(aes(y = pct ,
                            label = paste0(round(pct,2), '%')),
                        vjust=1, 
                        size = 3)
plot6 #+ coord_flip()
```

```{r}
base = ggplot(tableFreq, aes(x=locale,pct)) 
lolliplot1=base + geom_segment(aes(y = 0, 
                                   x = locale, 
                                   yend = pct, 
                                   xend = locale), color = "grey50") 
lolliplot1 + geom_point()
```

```{r}
tableFreq[order(tableFreq$pct),]
```

```{r}
tableFreqO=tableFreq[order(tableFreq$pct),]


base = ggplot(tableFreqO, aes(locale,pct)) 
lolliplot1=base + geom_segment(aes(y = 0, 
                                   x = locale, 
                                   yend = pct, 
                                   xend = locale), color = "gray") 
lolliplot2 = lolliplot1 + geom_point()
lolliplot2 + scale_x_discrete(limits=tableFreqO$locale)
```

```{r}
tableFreqO$gap=tableFreqO$pct-25
base = ggplot(tableFreqO, aes(locale,gap)) 

lolliplot1=base + geom_segment(aes(y = 0, 
                                   x = locale, 
                                   yend = gap, 
                                   xend = locale), color = "gray") 
lolliplot2 = lolliplot1 + geom_point()
lolliplot2 + scale_x_discrete(limits=tableFreqO$locale)
```

```{r}
tableFreqO$PositiveGap=ifelse(tableFreqO$gap>0,T,F)
base = ggplot(tableFreqO, aes(locale,gap,
                              color=PositiveGap)) 
lolliplot1=base + geom_segment(aes(y = 0, 
                                   x = locale, 
                                   yend = gap, 
                                   xend = locale), color = "gray") 
lolliplot2 = lolliplot1 + geom_point()
lolliplot2 + scale_x_discrete(limits=tableFreqO$locale)
```

```{r}
tableFreqO$PositiveGap=ifelse(tableFreqO$gap>0,T,F)

base = ggplot(tableFreqO, aes(locale,gap,color=PositiveGap,
                              label = round(gap,3)))
lolliplot1=base + geom_segment(aes(y = 0, 
                                   x = locale, 
                                   yend = gap, 
                                   xend = locale), color = "gray") 
lolliplot2=lolliplot1 + geom_point() 
lolliplot3= lolliplot2 + scale_x_discrete(limits=tableFreqO$locale) 

lolliplot3 + geom_text(nudge_x=0.3) 
```

```{r}
titleText2='Are all locations getting a fair share of public schools in WA?'
lolliplot3 + geom_text(nudge_x=0.3,show.legend = FALSE) + labs(title=titleText2,
                     x =NULL, 
                     y = NULL,
                     caption = 'Source: US Department of Education')
```

```{r}
table(eduwa$High.Grade,exclude = 'nothing')
```

```{r}
frqTabO=as.data.frame(prop.table(table(eduwa$High.Grade)))
names(frqTabO)=c('grade','pct')
frqTabO
```

```{r}
base = ggplot(frqTabO,aes(x=grade,y=pct))
base + geom_bar(stat = 'identity') 
```

```{r}
box1 = ggplot(eduwa, aes(y=as.numeric(High.Grade))) 
box1 = box1 + geom_boxplot() + coord_flip() 

box1
```

```{r}
ordLabels= levels(eduwa$High.Grade)

box2 = box1 + scale_y_continuous(labels=ordLabels,breaks=1:15)
box2
```

```{r}
titleText4="Distribution of grade offered by the public schools "
box3 = box2 + labs(title=titleText4,
                     x =NULL, 
                     y = NULL,
                     caption = 'Source: US Department of Education')
box3
```

```{r}
box4 = box3 + theme(panel.background = element_rect(fill = "white",
                                                          colour = "grey50"),
                   plot.caption = element_text(hjust = 1),
                    plot.title = element_text(hjust = 0.5))
box4
```


```{r}
pos_q1=     ggplot_build(box2)$data[[1]]$lower
pos_median= ggplot_build(box2)$data[[1]]$middle
pos_q3=     ggplot_build(box2)$data[[1]]$upper
```

```{r}
levels(eduwa$High.Grade)[c(pos_q1,pos_median,pos_q3)]
```

```{r}
library(summarytools)
freq(eduwa$High.Grade,style = 'rmarkdown') 
```

```{r}
length(unique(eduwa$Free.Lunch))
```

```{r}
summary(eduwa$Free.Lunch)
```

```{r}
eduwa3=eduwa[complete.cases(eduwa$Free.Lunch),]
dataHist=hist(eduwa3$Free.Lunch)
```

```{r}
base= ggplot(eduwa3,aes(x = Free.Lunch))  
h1= base + geom_histogram()
h1 
```

```{r}
dataHist
```

```{r}
ggplot_build(h1)$data[[1]]
```

```{r}
base= ggplot(eduwa3,aes(x = Free.Lunch))  
h1= base + geom_histogram(binwidth = 100,boundary=0) 
h1= h1 + stat_bin(binwidth = 100, aes(label=..count..), 
                  geom = "text",boundary = 0,vjust=-0.5)
h1
```

```{r}
h2 = h1 + scale_y_continuous(breaks=c(0,200,400,600,800,1000),
                                 limits = c(0, 1000),
                                 labels=scales::unit_format(suffix = ''))
h2
```

```{r}
h3 = h2 + scale_x_continuous(breaks=c(0,200,400,600,800,1000,1200,1400,1600,1800),
                                 limits = c(0, 1800),
                                 labels=scales::unit_format(suffix = ''))
h3
```

```{r}
hist(eduwa3$Free.Lunch,labels = T,xlab="Free Lunch")
```

```{r}
titleText5 = "Amount of kids in each school that have free lunch"
hist(eduwa3$Free.Lunch,labels = T,xlab="Free Lunch", xaxt="n",
     main = titleText5, sub = sourceText, ylim = c(0,1000))
axis(side=1, at=dataHist$breaks)
```

```{r}
tapply(eduwa$Student.Teacher.Ratio, eduwa$County, mean)
```

```{r}
tapply(eduwa$Student.Teacher.Ratio, eduwa$County, mean,na.rm=T)
```

```{r}
eduwa4=eduwa[complete.cases(eduwa$Student.Teacher.Ratio),]

tapply(eduwa4$Student.Teacher.Ratio, 
       eduwa4$County, 
       mean)
```

```{r}
TableMean=as.data.frame(meanValues)
TableMean
```

```{r}
titleTex6="Mean values of student-teacher ratio"
base= ggplot(TableMean,aes(x = TableMean$meanValues))
h6= base+geom_histogram(aes(fill=TableMean$meanValues), binwidth = 2,boundary=0)+
  stat_bin(binwidth = 2, aes(label=..count..),
           geom = "text", boundary = 0, vjust =-0.5)+
  labs(title=titleTex6,x=NULL, y=NULL, caption = sourceText) +
  theme(plot.title = element_text(hjust=0.5))
h6
```

```{r}
titleText7= "Density plot of student-teacher ratio"
base=ggplot(TableMean)
h7=base+stat_density(aes(x= meanValues),adjust=1,geom="line",kernel= "gaussian")+geom_vline(xintercept=mean(meanValues),linetype="dashed", lwd=1.5, col="green") + 
  geom_vline(xintercept =median(meanValues),lty="dashed", lwd=1.5,col="yellow")+
  labs(title=titleText7,x=NULL,y=NULL,caption= sourceText)+theme(plot.title=element_text(hjust=0.5))
h7
```

